
$('#writeToFile').click(function(){
				$.ajax({
					type: "POST",
					url: "abc.php",
					data: "",
					success: function(msg){
						alert(msg);
					},
					error: function(XMLHttpRequest, textStatus, errorThrown) {
						alert("Some error occured");
					}
					
				});
			});




<?php
 //write to file on button event

function buttonWrite()
{
$filename = 'button.txt';
@ $fp = fopen("messages/".$filename, 'wb');
if (!$fp)
{
    echo '<p><strong>Cannot generate message file</strong></p></body></html>';
    exit;
} 

$outputstring  = 'Hello, i have been generated by the button';

fwrite($fp, $outputstring);
}

?>

<html>

<head>
<title>Button Writer</title>
</head>

<body>
<button type="button" onclick="buttonWrite()">Write to File</button>
</body>

</html>